<?php

return [
    [
        'slug' => 'dashboard',
        'name' => 'Dashboard',
        'description' => 'Main analytics and overview dashboard',
        'icon' => 'dashboard',
        'order' => 1,
    ],
    [
        'slug' => 'buyers',
        'name' => 'Buyers Management',
        'description' => 'Manage all buyer/customer accounts',
        'icon' => 'users',
        'order' => 2,
    ],
    [
        'slug' => 'sellers',
        'name' => 'Sellers Management',
        'description' => 'Manage all seller stores/shops',
        'icon' => 'store',
        'order' => 3,
    ],
    [
        'slug' => 'products',
        'name' => 'Products & Services',
        'description' => 'Manage all products and services listed by sellers',
        'icon' => 'package',
        'order' => 4,
    ],
    [
        'slug' => 'orders',
        'name' => 'Orders Management',
        'description' => 'Manage all orders (buyers and sellers)',
        'icon' => 'shopping-cart',
        'order' => 5,
    ],
    [
        'slug' => 'transactions',
        'name' => 'Transactions',
        'description' => 'View and manage all financial transactions',
        'icon' => 'credit-card',
        'order' => 6,
    ],
    [
        'slug' => 'kyc',
        'name' => 'Store KYC',
        'description' => 'Verify and manage seller KYC documents',
        'icon' => 'shield-check',
        'order' => 7,
    ],
    [
        'slug' => 'subscriptions',
        'name' => 'Subscriptions',
        'description' => 'Manage seller subscription plans',
        'icon' => 'star',
        'order' => 8,
    ],
    [
        'slug' => 'promotions',
        'name' => 'Promotions',
        'description' => 'Manage seller promotions, coupons, and discounts',
        'icon' => 'tag',
        'order' => 9,
    ],
    [
        'slug' => 'social_feed',
        'name' => 'Social Feed',
        'description' => 'Manage seller social media posts and announcements',
        'icon' => 'rss',
        'order' => 10,
    ],
    [
        'slug' => 'all_users',
        'name' => 'All Users',
        'description' => 'Unified view of all users (buyers, sellers, admins)',
        'icon' => 'users',
        'order' => 11,
    ],
    [
        'slug' => 'balance',
        'name' => 'Balance Management',
        'description' => 'View and manage user wallet balances',
        'icon' => 'wallet',
        'order' => 12,
    ],
    [
        'slug' => 'chats',
        'name' => 'Chats',
        'description' => 'Monitor and manage user chats',
        'icon' => 'message-circle',
        'order' => 13,
    ],
    [
        'slug' => 'analytics',
        'name' => 'Analytics',
        'description' => 'Advanced analytics and reporting',
        'icon' => 'bar-chart',
        'order' => 14,
    ],
    [
        'slug' => 'leaderboard',
        'name' => 'Leaderboard',
        'description' => 'View and manage user leaderboards',
        'icon' => 'trophy',
        'order' => 15,
    ],
    [
        'slug' => 'support',
        'name' => 'Support',
        'description' => 'Manage customer support tickets',
        'icon' => 'headphones',
        'order' => 16,
    ],
    [
        'slug' => 'disputes',
        'name' => 'Disputes',
        'description' => 'Manage order and transaction disputes',
        'icon' => 'alert-triangle',
        'order' => 17,
    ],
    [
        'slug' => 'withdrawals',
        'name' => 'Withdrawal Requests',
        'description' => 'Approve or reject withdrawal requests',
        'icon' => 'dollar-sign',
        'order' => 18,
    ],
    [
        'slug' => 'ratings',
        'name' => 'Ratings & Reviews',
        'description' => 'Manage product and store ratings/reviews',
        'icon' => 'star',
        'order' => 19,
    ],
    [
        'slug' => 'referrals',
        'name' => 'Referral Management',
        'description' => 'Manage referral program settings and tracking',
        'icon' => 'user-plus',
        'order' => 20,
    ],
    [
        'slug' => 'notifications',
        'name' => 'Notifications',
        'description' => 'Create and manage system notifications',
        'icon' => 'bell',
        'order' => 21,
    ],
    [
        'slug' => 'seller_help',
        'name' => 'Seller Help Requests',
        'description' => 'Manage help requests from sellers',
        'icon' => 'help-circle',
        'order' => 22,
    ],
    [
        'slug' => 'settings',
        'name' => 'Settings',
        'description' => 'System configuration and admin management',
        'icon' => 'settings',
        'order' => 23,
    ],
];

